var digits, hour1, hour2, minute1, minute2, period, second1, second2, updateClock;

digits = $('.d');

hour1 = $('.h1');

hour2 = $('.h2');

minute1 = $('.m1');

minute2 = $('.m2');

second1 = $('.s1');

second2 = $('.s2');

period = $('.per');

updateClock = function() {
  var d, h, m, p, s;
  d = new Date();
  h = d.getHours();
  m = d.getMinutes();
  s = d.getSeconds();
  if (h >= 12) {
    p = 'pm';
  } else {
    p = 'am';
  }
  if (h >= 13) {
    h = '' + h - 12;
  } else {
    h = '' + h;
  }
  if (h < 10) {
    h = '0' + h;
  } else {
    h = '' + h;
  }
  if (h === '00') {
    h = '12';
  }
  if (m < 10) {
    m = '0' + m;
  } else {
    m = '' + m;
  }
  if (s < 10) {
    s = '0' + s;
  } else {
    s = '' + s;
  }
  digits.removeClass('d0 d1 d2 d3 d4 d5 d6 d7 d8 d9');
  hour1.addClass('d' + h.charAt(0));
  hour2.addClass('d' + h.charAt(1));
  minute1.addClass('d' + m.charAt(0));
  minute2.addClass('d' + m.charAt(1));
  second1.addClass('d' + s.charAt(0));
  second2.addClass('d' + s.charAt(1));
  period.removeClass('am pm');
  return period.addClass(p);
};

updateClock();

setInterval(updateClock, 250);

// ---
// generated by coffee-script 1.9.2